server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Esto es clave para Angular (SPA): si el navegador pide /pedidos
    # directamente, nginx debe servir igual index.html y dejar que
    # Angular Router decida que mostrar, en vez de dar 404.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
