server:
  port: 8082

spring:
  application:
    name: catalogo-service

  datasource:
    url: jdbc:postgresql://localhost:5432/catalogo360
    username: postgres
    password: CAMBIA-ESTA-CONTRASENA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/TU-TENANT-ID/v2.0